### ISSUE TITLE
Applying materials to PathExtrude3D

### ISSUE THREAD

**Issue by patrykkalinowski** [iiMidknightii/PathMesh3D#6]
Hi,
Thanks for building the plugin. I found it while searching for something more performant than CSGPolygon3D.

In my case, native Godot's CSGPolygon3D along Path3D works perfectly, apart from noticeable FPS hit, as my Path3D is modified every frame - therefore I cannot bake the mesh which is also regenerated every frame.

That also means that I need to apply material in real time and CSGPolygon3D allows that.

I was wondering if it's possible to add material support to your nodes, just like in CSGPolygon3D?

Best

**Comment by iiMidknightii** [comment]
@patrykkalinowski I updated the plugin to v1.2.0, which added a `material` property to `PathExtrude3D`.  It should behave almost exactly like `CSGPolygon3D`s material, including using the same UV space.  Let me know if it works for you.

**Comment by patrykkalinowski** [comment]
@iiMidknightii thanks for working on this!
I had a chance to test it out over the weekend.
Looks like UVs are working differently. I applied the same texture to CSGPolygon3D and PathExtrude3D.
I can play around with UV1 scale to tile a texture over CSGPolygon3D, but it doesn't work with PathExtrude3D. Seems like it ignores UV scale and always extends the image over the whole object.

Attaching small project to reproduce. Play around with UV1 offset and scale on both objects and you'll see the difference.

[path-extrude-test.zip](https://github.com/user-attachments/files/18825494/path-extrude-test.zip)

**Comment by patrykkalinowski** [comment]
You know what, I think I will be able to achieve most of the same with PathMesh3D. I didn't notice all mesh rotation options before. It's still not tiling exactly like I'd like to, but I'll keep experimenting

**Comment by iiMidknightii** [comment]
I'll take a look. I think I just need to account for the tiling in the material.

**Comment by iiMidknightii** [comment]
I'm still investigating this.  I'm not sure why, but Godot isn't respecting the UVs I'm setting.

**Comment by iiMidknightii** [comment]
@patrykkalinowski I released v1.3.0 now.  I think the behavior of the materials is finally matching CSGPolygon3D.  Let me know what you think.  I debated on splitting the material for the end caps into their own properties, but kept it this way so you could theoretically play around in CSGPolygon3D then directly apply it to PathExtrude3D.

**Comment by patrykkalinowski** [comment]
Just tested, works great! Thanks a lot!

UV works a little differently (I need to use different scale values compared to CSGPolygon3D), but I can achieve identical result.
